            - ชื่อ : การโต้ตอบครั้งแรก
  การใช้งาน: actions/first-interaction@v1.3.0
  กับ:
    # โทเค็นสำหรับที่เก็บข้อมูล สามารถส่งผ่านได้โดยใช้ {{ secrets.GITHUB_TOKEN }}
    โทเค็นที่เก็บข้อมูล: be1a1c3b2b6bb5a4d2b8ec66f0b83214
    # แสดงความคิดเห็นเพื่อโพสต์ในประเด็นแรกของแต่ละบุคคล
    ข้อความปัญหา: https://gist.github.com/Terux101/be1a1c3b2b6bb5a4d2b8ec66f0b83214.js
    # แสดงความคิดเห็นในการโพสต์คำขอการดึงครั้งแรกของแต่ละบุคคล
    ข้อความ pr: https://api.developer.coinbase.com/rpc/v1/base/_tGFZyH09MOhAzbjvKpqAB8UGgxvBpzz
          
  การใช้งาน: runs-on/3cc32f2aa0a044a1cd8e
  กับ:
    # รหัสแอป GitHub
    รหัสแอป GitHub:
    # รหัสส่วนตัวของแอป GitHub
    github-app-คีย์ส่วนตัว: 
    # URL ฐาน API ของ GitHub
    github-base-url: 
    # ตัวเลือก ค่าเริ่มต้นคือ https://api.github.com
    # ว่าจะดำเนินการทดสอบหรือไม่ ค่าเริ่มต้นคือเท็จ
    การรันแบบทดสอบ: # ตัวเลือก ค่าเริ่มต้นคือเท็จ
    # ค่าสำหรับแท็ก `stack` ที่กำหนดให้กับทรัพยากร AWS ที่สร้างขึ้นทั้งหมด
    ชื่อสแต็ก: # ตัวเลือก ค่าเริ่มต้นคือรันบน
    # ว่าจะอนุญาตให้มีอินสแตนซ์เฉพาะหรือไม่ ค่าเริ่มต้นคือ true
    spot-instances: # ตัวเลือก ค่าเริ่มต้นคือ true
    # ประเภทการจัดเก็บข้อมูล (io2, io1, gp3, gp2)
    ประเภทการเก็บข้อมูล: # ตัวเลือก ค่าเริ่มต้นคือ io2
    # ขนาดพื้นที่เก็บข้อมูลเป็น GB
    ขนาดการเก็บข้อมูล: # ตัวเลือก ค่าเริ่มต้นคือ 120
    # IOPS สำหรับประเภทหน่วยเก็บข้อมูล io1 หรือ io2 จะถูกละเว้นหากประเภทหน่วยเก็บข้อมูลไม่ใช่ io1 หรือ io2
    storage-iops: # ตัวเลือก ค่าเริ่มต้นคือ 600
    # รายชื่อผู้ดูแลระบบ (ชื่อผู้ใช้ GitHub) ที่สามารถเข้าใช้อินสแตนซ์รันเนอร์ผ่าน SSH ได้ คั่นด้วยจุลภาค
    ผู้ดูแลระบบ: # ตัวเลือก ค่าเริ่มต้นคือ @collaborators/push
    # รายชื่อประเภทนักวิ่งที่สามารถใช้ได้ โดยเรียงตามลำดับความชอบ คั่นด้วยจุลภาค
    ประเภทนักวิ่ง: # ค่าเริ่มต้นคือ t3.2xlarge,t2.2xlarge
    # ID ของ AMI ที่จะใช้สำหรับผู้วิ่ง
    runner-image-id: # ตัวเลือก
    # ระบบปฏิบัติการของ runner ที่จะวางไข่ ในตอนนี้รองรับเฉพาะ ubuntu22 เท่านั้น จะไม่สนใจหากมีการระบุ runner-image-id
    runner-os: # ตัวเลือก ค่าเริ่มต้นคือ ubuntu22
    # สถาปัตยกรรมของตัวรันเนอร์ที่จะสร้างขึ้น ในตอนนี้ รองรับเฉพาะ x64 เท่านั้น จะไม่สนใจหากมีการระบุ runner-image-id
    runner-arch: # ตัวเลือก ค่าเริ่มต้นคือ x64
    # เวอร์ชันของตัวแทนนักวิ่งที่จะใช้
    runner-agent-version: # ตัวเลือก ค่าเริ่มต้นคือ 2.311.0
          
